name: Auto Update Structure Index

on:
  push:
    paths:
      - "structures/**/*.json"
      - "scripts/generateIndex.js"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run index generator
        run: node scripts/generateIndex.js

      - name: Commit and push updated index
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index/structureIndexMap*.json
          git commit -m "🔄 Auto-update structure index"
          git push origin main