name: Update Structure Index

on:
  push:
    paths:
      - 'structures/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run generateIndex script
        run: node scripts/generateIndex.js

      - name: Set up Git user
        run: |
          git config user.name "MICHIHAL"
          git config user.email "sakiyayoi@gmail.com"

      - name: Commit and push updated index
        run: |
          git add index/structureIndexMap.json
          git commit -m "🔄 Auto-update structure index"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
